main/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='main'

urlpatterns = [
    path('', views.IndexPageView.as_view(), name="index"),
    path('Contact-Us', views.ContactCreateView.as_view(), name="contact"),
    path('About-Us', views.AboutPageView.as_view(), name="about"),
]

meetlab/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('Our-Services/',include('services.urls')),
    path('photos/',include('photos.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
        urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
admin.site.site_header = "Meet Studio & Labs Admin"
admin.site.site_title = "MS&L Admin Portal"
admin.site.index_title = "Welcome to Meet Studio & Lab Portal"

photos/urls.py
from django.contrib import admin
from django.urls import path
from main import views
app_name='photos'

urlpatterns = [
    # path('', views.index, name="index"),
    # path('Contact-Us', views.contact, name="contact"),
]

services/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='services'

urlpatterns = [
    path('', views.ServicePageView.as_view(), name="index"),
]

main/models.py
from django.db import models

class Contact(models.Model):    
    name=models.CharField(max_length=60)
    email=models.EmailField(blank=True,null=True)
    no=models.CharField(max_length=13)
    msg=models.TextField()
    address=models.TextField()

    def __str__(self):
        return self.name

class Slider(models.Model):
    name=models.CharField(max_length=60)
    img=models.ImageField(upload_to='slider/')

photos/models.py
from django.db import models
from services.models import Services

class Photos(models.Model):
    widthChoice=[
        ('0','4x1'),
        ('width-1','3x1'),
        ('width-2','2x1')
    ]
    name=models.CharField(max_length=60)
    desc=models.TextField()
    width=models.CharField(max_length=10,choices=widthChoice)
    img=models.ImageField(upload_to='photos/')
    category=models.OneToOneField(Services,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

services/models.py
from django.db import models

class Services(models.Model):
    alignChoice=[
        ('l','Left'),
        ('r','Right')
    ]
    name=models.CharField(max_length=60)
    desc=models.TextField()
    align=models.CharField(max_length=10,choices=alignChoice)
    img=models.ImageField(null=True, blank=True, upload_to='services/')

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from .models import Contact

class ContactForm(ModelForm):
    class Meta:        
        cls='form-control input-group mb-3'  
        model= Contact
        fields='__all__'
        labels={
            'name':_(""),
            'email':_(""),
            'no':_(""),
            'msg':_(""),
            'address':_(""),
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':cls,'placeholder':'Enter Name'}),
            'email': forms.TextInput(attrs={'class':cls,'placeholder':'Enter Email'}),            
            'no': forms.TextInput(attrs={'class':cls,'placeholder':'Enter Mobile No'}),
            'address': forms.Textarea(attrs={'class':cls,'rows':3,'placeholder':'Enter Address'}),
            'msg': forms.Textarea(attrs={'class':cls,'placeholder':'Message/Requirement'}),
        }
        help_texts:{
            'name':_('John Doe')
        }    
        error_messages:{
            'name':{
                'max_length':_("Name should be 60 words")
            }
        }

main/views.py
from django.core.mail import send_mail,EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from django.shortcuts import render,redirect,reverse
from .models import Contact,Slider
from services.models import Services
from photos.models import Photos
from .forms import ContactForm
from django.views import generic
from django.conf import settings



class IndexPageView(generic.ListView):
    model=Services
    template_name = "main/index.html"
    query_set= Services.objects.all()
    context_object_name="services"

    def get_context_data (self, ** kwargs):
        context = super (). get_context_data (** kwargs)
        context ['sli'] = Slider.objects.all()
        context ['photos'] = Photos.objects.all()
        return context

class AboutPageView(generic.ListView):
    model=Services
    template_name = "main/about.html"
    query_set= Services.objects.all()
    context_object_name="services"

    def get_context_data (self, ** kwargs):
        context = super (). get_context_data (** kwargs)
        context ['sli'] = Slider.objects.all()
        context ['photos'] = Photos.objects.all()
        return context

class ContactCreateView(generic.CreateView):
    model = Contact
    template_name = "main/contact.html"
    form_class=ContactForm

    def form_valid(self, form):
        cd=form.clean()
        html_content=render_to_string("email/contactAdmin.html",cd)
        text_content=strip_tags(html_content)
        email=EmailMultiAlternatives(
            "New Query",
            text_content,
            settings.DEFAULT_FROM_EMAIL,
            ['help@meetphotolab.in','starlordali@gmail.com','meetstudiolucknow@gmail.com']            
        )
        email.attach_alternative(html_content,"text/html")
        print(email.send())
        return super(ContactCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('main:contact')

photos/views.py
from django.shortcuts import render

# Create your views here.

services/views.py
from django.shortcuts import render
from django.views import generic
from .models import Services

class ServicePageView(generic.ListView):
    model=Services
    template_name = "services/index.html"
    query_set= Services.objects.all()
    context_object_name="services"

    def get_context_data (self, ** kwargs):
        context = super (). get_context_data (** kwargs)
        return context

templates/layout/base.html
<!doctype html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=utf-8" />
{% include "layout/head.html" %}
<body>
    {% include "layout/header.html" %}
    {% block content %}
    {% endblock content %}
    {% include "layout/footer.html" %}
    {% include "layout/foot.html" %}
</body>
</html>

templates/layout/foot.html
{% load static %}
<script src="{% static 'main/js/jquery-1.12.1.min.js' %}"></script>
<script src="{% static 'main/js/popper.min.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
<script src="{% static 'main/js/jquery.magnific-popup.js' %}"></script>
<script src="{% static 'main/js/swiper.min.js' %}"></script>
<script src="{% static 'main/js/jquery.filterizr.min.js' %}"></script>
<script src="{% static 'main/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'main/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'main/js/slick.min.js' %}"></script>
<script src="{% static 'main/js/swiper.min.js' %}"></script>
<script src="{% static 'main/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'main/js/waypoints.min.j' %}s"></script>
<script src="{% static 'main/js/contact.js' %}"></script>
<script src="{% static 'main/js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'main/js/jquery.form.js' %}"></script>
<script src="{% static 'main/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'main/js/mail-script.js' %}"></script>
<script src="{% static 'main/js/custom.js' %}"></script>
<script src="{% static 'main/js/jssor.slider.min.js' %}"></script>
<script src="{% static 'main/js/slider.js' %}"></script>

templates/layout/footer.html
{% load static %}
<footer class="footer-area">
    <div class="container">
        <div class="row justify-content-between">
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="single-footer-widget">
                    <h4>Our Service</h4>
                    <ul>
                        <li><a href="#">Urgent Photo</a></li>
                        <li><a href="#">Photo Frame's</a></li>
                        <li><a href="#">Wedding Photography & Videography</a></li>
                        <li><a href="#">Candid Photography</a></li>
                        <li><a href="#">Cinematic Videography</a></li>
                        <li><a href="#">Pre-Wedding Shoot</a></li>
                        <li><a href="#">Drone, Crane, LED Wall Available</a></li>
                        <li><a href="#">Mug, T-Shirt, Pillow, Key-Ring, etc. Printing</a></li>
                    </ul>

                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="single-footer-widget footer_icon">
                    <h4>Contact Info</h4>
                    <p>Shop No - 4 , 60 Feet Road Jankipuram Vistar Yojna Lucknow (U.P.) 226021</p>
                    <ul>
                        <li><a href="#"><i class="ti-mobile"></i>+91- 8840235103</a></li>
                        <li><a href="#"><i class="ti-email"></i>support@meetphotolab.in</a></li>
                        <li><a href="www.meetphotolab.in"><i class="ti-world"></i> www.meetphotolab.in</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="single-footer-widget footer_3">
                    <h4>Social Platforms</h4>
                    <div class="footer_img">
                        <div class="single_footer_img">
                            <img src="{% static 'main/img/footer_img/footer_img_1.png' %}" alt="">
                            <i class="ti-instagram"></i>
                        </div>
                        <div class="single_footer_img">
                            <img src="{% static 'main/img/footer_img/footer_img_2.png' %}" alt="">
                            <i class="ti-instagram"></i>
                        </div>
                        <div class="single_footer_img">
                            <img src="{% static 'main/img/footer_img/footer_img_3.png' %}" alt="">
                            <i class="ti-instagram"></i>
                        </div>
                        <div class="single_footer_img">
                            <img src="{% static 'main/img/footer_img/footer_img_4.png' %}" alt="">
                            <i class="ti-instagram"></i>
                        </div>
                        <div class="single_footer_img">
                            <img src="" alt="">
                            <i class="ti-instagram"></i>
                        </div>
                        <div class="single_footer_img">
                            <img src="{% static 'main/img/footer_img/footer_img_6.png' %}" alt="">
                            <i class="ti-instagram"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-3">
                <div class="single-footer-widget footer_2">
                    <h4>Newsletter</h4>
                    <p>Stay updated with our latest trends see heaven so said place fruit.
                    </p>
                    <div class="form-wrap" id="mc_embed_signup">
                        <form target="_blank"
                            action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                            method="get" class="form-inline">
                            <input class="form-control" name="EMAIL" placeholder="Your Email Address"
                                onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your Email Address '"
                                required="" type="email">
                            <button class="btn btn-default text-uppercase"><i class="ti-angle-right"></i></button>
                            <div style="position: absolute; left: -5000px;">
                                <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value=""
                                    type="text">
                            </div>

                            <div class="info"></div>
                        </form>
                    </div>
                    <div class="social_icon">
                        <a href="#"> <i class="ti-facebook"></i> </a>
                        <a href="#"> <i class="ti-twitter-alt"></i> </a>
                        <a href="#"> <i class="ti-instagram"></i> </a>
                        <a href="#"> <i class="ti-skype"></i> </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="copyright_part_text text-center">
                    <p class="footer-text m-0">
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class="ti-heart" aria-hidden="true"></i> by <a href="" target="_blank">Ali Media Solutions</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/layout/head.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{title}}</title>
    <link rel="icon" href="{% static 'main/img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/flaticon.cs' %}s">
    <link rel="stylesheet" href="{% static 'main/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/swiper.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/slick.css' %}  ">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/slider.css' %}">
</head>

templates/layout/header.html
{% load static %}
<header class="main_menu home_menu">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-brand" href="{% url 'main:index' %}"> <img src="{% static 'main/img/logo.png' %}" alt="Meet Photo Lab"> </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="menu_icon"><i class="fas fa-bars"></i></span>
                    </button>

                    <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:index' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:about' %}">about</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'services:index' %}">services</a>
                            </li>
                            {% comment %} <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownpro"
                                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    portfolio
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownpro">
                                    <a class="dropdown-item" href="portfolio.html">portfolio</a>
                                    <a class="dropdown-item" href="portfolio_details.html">portfolio details</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown"
                                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Blog
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="blog.html"> blog</a>
                                    <a class="dropdown-item" href="single-blog.html">Single blog</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown1"
                                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    pages
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                                    <a class="dropdown-item" href="elements.html">Elements</a>
                                </div>
                            </li> {% endcomment %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:contact' %}">contact</a>
                            </li>
                        </ul>
                    </div>
                    {% comment %} <div class="dropdown cart">
                        <a class="dropdown-toggle" href="#" id="navbarDropdown3" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="flaticon-bag"></i>
                        </a>
                    </div> {% endcomment %}
                </nav>
            </div>
        </div>
    </div>
</header>

templates/main/about.html
{% extends 'layout/base.html' %}
{% block content %}
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner text-center">
                        <div class="breadcrumb_iner_item">
                            <h2>About <span>us</span></h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb start-->

    <!--::about_us part start::-->
    <section class="about_us section_padding">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-8">
                    <div class="about_us_text text-center">
                        <h5>About our studio</h5>
                        <h2>The Camera Is An Instrument That Teaches People
                            how to See without a Camera</h2>
                        <p>It’s the end of summer the sweltering heat makes human
                            sweat in the night and makes the plants and trees wilt
                            even in the moonlit nights. The eastern wind breeze brings
                            an eerie feeling, that the monsoon clouds are soon coming,
                            there is a strange silence in the ears, the sky gets darker
                            and darker, the flash of lightning illuminates the dark skies,
                            the sound of thunder fills the heart with fear.</p>
                        <a href="#" class="btn_2">read more</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--::about_us part end::-->

    <!-- intro_video_bg start-->
    <section class="intro_video_bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro_video_iner text-center">
                        <h2>Our project video</h2>
                        <div class="intro_video_icon">
                            <a id="play-video_1" class="video-play-button popup-youtube"
                                href="">
                                <span class="ti-control-play"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- intro_video_bg part start-->

    <!--::review_part part start::-->
    <section class="review_part section_padding">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-6 col-lg-6">
                    <div class="review_img">
                        <img src="img/review_bg.png" alt="">
                    </div>
                </div>
                <div class="col-md-6 col-lg-5">
                    <div class="review_slider owl-carousel">
                        <div class="review_part_text">
                            <h2>With efficiency to
                                unlock more opportunities</h2>
                            <p>Saw shall light. Us their to place had creepeth day
                                night great wher appear to. Hath, called, sea called,
                                gathering wherein open make living Female itself
                                gathering man. Waters and, two. Bearing. Saw she'd
                                all let she'd lights abundantly blessed.</p>
                            <h3>Mitchel Jeferson, <span>CEO of softking</span> </h3>
                        </div>
                        <div class="review_part_text">
                            <h2>With efficiency to
                                unlock more opportunities</h2>
                            <p>Saw shall light. Us their to place had creepeth day
                                night great wher appear to. Hath, called, sea called,
                                gathering wherein open make living Female itself
                                gathering man. Waters and, two. Bearing. Saw she'd
                                all let she'd lights abundantly blessed.</p>
                            <h3>Mitchel Jeferson, <span>CEO of softking</span> </h3>
                        </div>
                        <div class="review_part_text">
                            <h2>With efficiency to
                                unlock more opportunities</h2>
                            <p>Saw shall light. Us their to place had creepeth day
                                night great wher appear to. Hath, called, sea called,
                                gathering wherein open make living Female itself
                                gathering man. Waters and, two. Bearing. Saw she'd
                                all let she'd lights abundantly blessed.</p>
                            <h3>Mitchel Jeferson, <span>CEO of softking</span> </h3>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
    
{% endblock content %}

templates/main/contact.html
{% extends 'layout/base.html' %}
{% block content %}
  <section class="breadcrumb breadcrumb_bg ">
    <div class="container mb-n5">
      <div class="row">
        <div class="col-lg-12">
          <div class="breadcrumb_iner text-center">
            <div class="breadcrumb_iner_item">
              <h2>Get in Touch !!</h2>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="contact-section ">
    <div class="container">
      <div class="d-sm-block mb-5 pb-4">
          <div id="map" style="min-height: 480px;"></div>
            <script>
              let marker;
              function initMap() {
                const meetmap = { lat: 26.927186467186075, lng: 80.94336747934263 };
                const map = new google.maps.Map(document.getElementById("map"), {
                  zoom: 21,
                  center:meetmap,
                  streetViewControl: true,
                });
                const contentString =
                  '<div id="content">' +
                  '<div id="siteNotice">' +
                  "</div>" +
                  '<h1 id="firstHeading" class="firstHeading">Meet Studio & Labs</h1>' +
                  '<div id="bodyContent">' +
                  "<p><b>Best Photographer In Aliganj<br> Best Photographer In Jankipuram </b><br>" +
                  "Surbhi Complex, Jankipuram Extension Saat Feeta Road, Sultanpur Village, Jankipuram Vistar Lucknow, Uttar Pradesh 226021 India</p>"+
                  '<p> <a href="https://maps.google.com/maps?ll=26.927395,80.943367&z=20&t=m&hl=en-US&gl=US&mapclient=apiv3&cid=12513459244328035560">' +
                  "View on Google Maps</a></p>" +
                  "</div>" +
                  "</div>";
                  const infowindow = new google.maps.InfoWindow({
                    content: contentString,
                  });
                  marker = new google.maps.Marker({
                  position: meetmap,
                  map,
                  draggable: true,
                  animation: google.maps.Animation.BOUNCE,
                  title: "Meet Studio & Labs",
                });
                marker.addListener("click", () => {
                  infowindow.open(map, marker);
                });
              }
            </script>
            <script
              src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDNL0TjVEGos4PhmnnidbMzMBlYUm9dvK4&callback=initMap&libraries=&v=weekly"
              async
            ></script>
      </div>        
      <div class="row">
        <div class="col-12">
          <h2 class="contact-title">Get in Touch</h2>
        </div>
        <div class="col-lg-8">
          <form class="form-contact" action="Contact-Us" method="post" >
            {% csrf_token %}            
            <div class="row">
                {{form}}
            </div> 
            <div class="form-group mt-3">
              <button type="submit" class="button-contactForm btn_2">Send Message </button>
            </div>
          </form>
        </div>
        <div class="col-lg-4">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>Buttonwood, California.</h3>
              <p>Rosemead, CA 91770</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3>00 (440) 9865 562</h3>
              <p>Mon to Fri 9am to 6pm</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3>support@meetphotolab.in</h3>
              <p>Send us your query anytime!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}